name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: docker build & push
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10, 12, 14]
    steps:
      - name: checkout scm
        uses: actions/checkout@v2
      - name: docker/build-push
        uses: docker/build-push-action@v1
        with:
          username: hongaar
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: hongaar/firebase-action
          build_args: version=${{ matrix.node-version }}
          tags: ${{ matrix.node-version }}
